CREATE TABLE usuarios (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  login VARCHAR(30) NOT NULL,
  password VARCHAR(32) NOT NULL,
  nickname VARCHAR(40) NOT NULL,
  email VARCHAR(40) NOT NULL UNIQUE
);

CREATE TABLE categorias (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nombre_categoria VARCHAR(30) NOT NULL
);

CREATE TABLE etiquetas (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nombre_etiqueta VARCHAR(30) NOT NULL
);

CREATE TABLE posts (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  titulo VARCHAR(130) NOT NULL,
  fecha_publicacion TIMESTAMP NULL DEFAULT NULL,
  contenido TEXT NOT NULL,
  estatus CHAR(8) DEFAULT "activo",
  id_usuario INT DEFAULT NULL,
  id_categoria INT DEFAULT NULL,
  CONSTRAINT FOREIGN KEY (id_categoria) REFERENCES categorias (id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FOREIGN KEY (id_usuario) REFERENCES usuarios (id) ON DELETE NO ACTION ON UPDATE CASCADE
  );

CREATE TABLE comentarios (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  cuerpo_comentario TEXT NOT NULL,
  id_usuario INT NOT NULL,
  id_post INT NOT NULL,
  CONSTRAINT FOREIGN KEY (id_post) REFERENCES posts (id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FOREIGN KEY (id_usuario) REFERENCES usuarios (id) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE posts_etiquetas (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  id_post INT NOT NULL,
  id_categoria INT DEFAULT NULL,
  CONSTRAINT FOREIGN KEY (id_post) REFERENCES posts (id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FOREIGN KEY (id_categoria) REFERENCES categorias (id) ON DELETE NO ACTION ON UPDATE CASCADE
);
